services:
  bot:
    build: .
    secrets:
      - bot_token
      - admin_user_ids
      - serper_api_key
      - ai_studio_api_key
      - db_user
      - db_password
      - db_name
    restart: always
    depends_on:
      - db
      - redis # Добавляем зависимость от Redis
    volumes:
      - ./logs:/app/logs

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB_FILE: /run/secrets/db_name
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    secrets:
      - db_user
      - db_password
      - db_name
    restart: always

  # --- [НОВЫЙ СЕРВИС REDIS ДЛЯ FSM] ---
  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis_data:/data

  backup:
    image: prodrigestivill/postgres-backup-local
    restart: always
    depends_on:
      - db
    secrets:
      - db_user
      - db_password
      - db_name
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB_FILE: /run/secrets/db_name
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      SCHEDULE: '@daily'
      BACKUP_KEEP_DAYS: 7
      BACKUP_FILENAME: 'backup-%Y-%m-%d-%H-%M-%S.sql.gz'
    volumes:
      - backups:/backups

volumes:
  postgres_data:
  backups:
  redis_data: # Добавляем том для Redis, чтобы состояния не терялись

secrets:
  bot_token:
    file: ./bot_token.txt
  admin_user_ids:
    file: ./admin_user_ids.txt
  serper_api_key:
    file: ./serper_api_key.txt
  ai_studio_api_key:
    file: ./ai_studio_api_key.txt
  db_user:
    file: ./db_user.txt
  db_password:
    file: ./db_password.txt
  db_name:
    file: ./db_name.txt