services:
  bot:
    build: .
    secrets:
      - bot_token
      - admin_user_ids
      - serper_api_key
      - ai_studio_api_key
      - db_user
      - db_password
      - db_name
    restart: always
    depends_on:
      - db
    volumes:
      # Пробрасываем папку с логами наружу, чтобы они не терялись при перезапуске контейнера
      - ./logs:/app/logs

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB_FILE: /run/secrets/db_name
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    secrets:
      - db_user
      - db_password
      - db_name
    restart: always

  # --- [НОВЫЙ СЕРВИС ДЛЯ БЭКАПОВ] ---
  backup:
    image: prodrigestivill/postgres-backup-local
    restart: always
    depends_on:
      - db
    secrets:
      - db_user
      - db_password
      - db_name
    environment:
      POSTGRES_HOST: db # Имя сервиса базы данных
      POSTGRES_DB_FILE: /run/secrets/db_name
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      # Расписание в формате cron. '@daily' означает "каждый день в полночь".
      SCHEDULE: '@daily'
      # Хранить бэкапы за последние 7 дней. Старые будут автоматически удаляться.
      BACKUP_KEEP_DAYS: 7
      # Формат имени файла бэкапа
      BACKUP_FILENAME: 'backup-%Y-%m-%d-%H-%M-%S.sql.gz'
    volumes:
      # Монтируем новый том для хранения бэкапов
      - backups:/backups

volumes:
  postgres_data:
  # --- [НОВЫЙ ТОМ ДЛЯ БЭКАПОВ] ---
  backups:

secrets:
  bot_token:
    file: ./bot_token.txt
  admin_user_ids:
    file: ./admin_user_ids.txt
  serper_api_key:
    file: ./serper_api_key.txt
  ai_studio_api_key:
    file: ./ai_studio_api_key.txt
  db_user:
    file: ./db_user.txt
  db_password:
    file: ./db_password.txt
  db_name:
    file: ./db_name.txt